### ISSUE TITLE
AnimationList生成的时候格式错误

### ISSUE THREAD

**Issue by liujin1992112** [lyzz0612/csb2csd#5]
![image](https://user-images.githubusercontent.com/12068652/114651820-3f7e9100-9d17-11eb-928c-78705de520ec.png)
能留一个qq或者微信的联系方式吗？最近工程csd文件丢失需要还原,中途遇到问题,需要和您沟通一下，谢谢

**Comment by labbbirder** [comment]
看起来作者很久不维护了，可以先用这个pr版本 #8
