### ISSUE TITLE
转化失败，能提供一个文件夹批量转化的功能吗？

### ISSUE THREAD

**Issue by zuoyanshun** [lyzz0612/csb2csd#6]
D:\csb2csd-master>python convert.py cocos_res/UI/BattlePass/BattlePassUnlock.csb
error no match className: WeCLabelOptions

**Comment by labbbirder** [comment]
#8 可以试试这个pr

**Comment by liujin1992112** [comment]
批量将文件夹csb转换为csd的脚本，只需要将此脚本放到convert,py同级目录就可以了，注意最好将批处理的文件夹备份，我将csb转换为csd后，会将csb文件删除掉
import os

def walkFile(file):
    for root, dirs, files in os.walk(file):
        for f in files:
            path = os.path.join(root, f)
            if path.endswith('.csb'):
                inPath = path
                outPath = path.replace('.csb', '.csd')

                cmd = 'python convert.py ' + inPath + ' ' + outPath
                os.system(cmd)
                os.remove(inPath)
                                
        for d in dirs:
            "print(os.path.join(root, d))"

walkFile("E:\\Work\\summoner\\lyzz0612-csb2csd\\res")    


![image](https://user-images.githubusercontent.com/12068652/129142436-9930ef2f-64b1-49e7-9f4d-5a2e284fe15b.png)
